ipo/src/lib.rs, ips/src/lib.rs
- Update ips FRAMEv2 syntax
- Update ipo FRAMEv2 syntax
=> Update ips and ipo FRAMEv2 syntax

.github/workflows/build.yml, Cargo.toml
This PR makes the repo a Cargo workspace (for easier CI) and also implements the CI checks.
=> Added github workflow for CI

ipo/src/lib.rs, ips/src/lib.rs, ipt/src/lib.rs
- Added IPS collection create function
- Added IPS class create function
- Added IPS create function
=> Feat: add ips create function

ipt/README.md, ipt/src/lib.rs
=> Fix: update `ammend` typo

ipt/src/lib.rs
- Added `mint` function
- IPS creation still in ipt pallet, next to be moved to ips pallet after all ipt functions be implemented.
=> Feat: WIP add `mint` function in ipt pallet

ipt/src/lib.rs
- Add `burn` function in ipt pallet
- Fix ips storage logic
=> WIP add `burn` function in ipt pallet

ips/Cargo.toml, ips/src/lib.rs, ipt/src/lib.rs, ipt/src/mock.rs, ipt/src/tests.rs
- Add tests.rs in ipt pallet
- Add mock.rs in ipt pallet
=> Feat: add test for ipt pallet

ipt/src/lib.rs
- Add `amend` function in ipt pallet
=> Feat: add amend fn in ipt pallet

ips/src/lib.rs
- Add `list` function in ips pallet
- Add `is_owner` function in ips pallet
=> Feat: add list function in ips pallet

ips/src/lib.rs
- Add buy fuction in ipt pallet
=> Feat WIP: add buy function in ips pallet

ips/src/lib.rs
- Add `destroy` function in ips pallet
=> Feat WIP: add destroy function in ips pallet

ips/Cargo.toml, ips/src/lib.rs, ipt/Cargo.toml, ipt/src/lib.rs, primitives/Cargo.toml, primitives/src/lib.rs
- Primitives to be used accross InvArch Pallet Library
=> Feat: add primitives pallet

ipo/Cargo.toml, ipo/src/lib.rs, primitives/src/lib.rs
- Add `issue` function ipo pallet
- Add ipo struct in primitives pallet
=> Feat: add issue fn in ipo pallet

ipo/src/lib.rs
- Add `transfer` function -> Transfer some liquid free balance to another account.
- Issue #33
=> Feat: add transfer function in ipo pallet

ipo/src/lib.rs
- Add `set_balance` function in ipo balance
- [Need help] implement more logic for free and reserved balance.
=> Feat WIP: add set-balance function in ipo pallet

ipt/Cargo.toml, primitives/Cargo.toml
This PR upgrades the substrate version of primitives and IPT pallet to the tag: monthly-2021-09+1.
=> Substrate upgraded in primitives and IPT pallet

ipo/README.md, ipo/src/lib.rs, ipt/Cargo.toml, primitives/src/lib.rs
- Add `bind` function in ipo pallet
- Add `is_bond` properties in primitives pallet
- Update asset `id` to `ipo_id` in Readme
=> Feat WIP: Add bind function in ipo pallet

ipo/README.md, ipo/src/lib.rs, ipt/src/mock.rs
- Add `unbind` function in ipo pallet
- Add `BaseCallFilter` in mock ipt pallet (for testing)
- Update Readme.
=> Feat: add unbind function in ipo pallet

ipt/src/lib.rs
This PR properly configures the IPT pallet to be usable in the node.
=> Properly configured the IPT pallet

ips/Cargo.toml, ips/src/lib.rs, ipt/src/lib.rs, primitives/src/lib.rs
This PR should have the IPS pallet ready to be used in the node.
=> Properly configured IPS pallet

ips/src/lib.rs
This PR fixes the IpsData type by specifying it as a Vec<IptId>.
=> Fixed the IpsData type

ipo/Cargo.toml, ipo/src/lib.rs, ipt/src/lib.rs, ipt/src/mock.rs, ipt/src/tests.rs, primitives/src/lib.rs
This PR fixes the Amend function that was actually minting new IPTs instead of changing the original, it also fully implements unit tests for all functions. Closes #20
=> IPT Tests + Amend Fixed

ipo/src/lib.rs, ips/src/lib.rs
- Remove redundant get balance function
- Remove unused AccountData
- Simplify set balance function
- Add event to transfer function
=> Update ipo pallet

ips/src/lib.rs, ips/src/tests.rs
this PR fixes the IPS buy function not transfering the IPTs to the new owner of the IPS.
=> Buy function now also transfers the IPTs tied to the IPS

dev/src/lib.rs, primitives/src/lib.rs
- Add `add` function in DEV pallet
=> Add `add function` in DEV pallet

dev/src/lib.rs
- Add `update_interaction` function
- Need further refactor
=> Feat: Add update function in DEV pallet

Cargo.toml, ips/Cargo.toml, ips/src/lib.rs, ips/src/mock.rs, ipt/Cargo.toml, ipt/src/lib.rs, ipt/src/mock.rs, primitives/Cargo.toml, primitives/src/lib.rs
This PR implements changes necessary for using pallet_assets for IP Ownership tokens.
=> Changes for pallet_assets integration

ip-staking/Cargo.toml, ip-staking/README.md, ip-staking/src/lib.rs
=> Add IP Staking Pallet

ipr/src/lib.rs
=> IPR Pallet

ips/src/lib.rs, ipt/src/lib.rs
=> Matheus checks+reformatting

ipt/src/lib.rs
=> feat: Multisig extrinsics

ips/src/lib.rs, ipt/src/lib.rs
This PR will fix issues found in the INV4 pallets on internal testing.
=> General fixes for INV4 pallets

ips/src/lib.rs, ipt/src/lib.rs
=> Fix for a couple pallet-ipt bugs

INV4/pallet-ipt/Cargo.toml, INV4/pallet-ipt/src/lib.rs, INV4/pallet-ipt/src/mock.rs, INV4/pallet-ipt/src/tests.rs
Add Ipt unit tests
closes #116
=> IPT Unit Tests

INV4/pallet-ips/src/lib.rs, INV4/pallet-ips/src/tests.rs
Empty appending now should return an error
resolves #134
=> Fix: Empty appending when not the owner

INV4/pallet-ipl/src/lib.rs, INV4/pallet-ips/src/lib.rs, INV4/pallet-ips/src/tests.rs, INV4/pallet-ipt/src/lib.rs, INV4/pallet-ipvm/src/lib.rs, primitives/src/lib.rs
=> Fix percent being non-inclusive

INV4/pallet-ipl/src/lib.rs, INV4/pallet-ipl/src/mock.rs, INV4/pallet-ipl/src/tests.rs
Make unit tests for pallet-ipl
=> IPL Unit Tests

INV4/README.md, INV4/pallet-ipf/README.md, INV4/pallet-ipl/README.md, INV4/pallet-ips/README.md, INV4/pallet-ipt/README.md, README.md
=> Update testing documentation

INV4/pallet-ipl/src/lib.rs, INV4/pallet-ips/src/benchmarking.rs, INV4/pallet-ipt/Cargo.toml, INV4/pallet-ipt/src/benchmarking.rs, primitives/src/lib.rs
Duplicate of https://github.com/InvArch/InvArch-Node/pull/92 as this is a dependency for that pull
=> Fix benchmark issues with Licenses & Call

INV4/pallet-inv4/src/ipl.rs, INV4/pallet-inv4/src/ips.rs, INV4/pallet-inv4/src/ipt.rs, INV4/pallet-inv4/src/lib.rs, INV4/pallet-ipf/src/lib.rs, primitives/src/lib.rs
Added helpful comments throughout the INV4 pallet except for part of ipt.rs and ipl.rs.
#170 
#171 
#172
#173
#174
=> INV4 pallet add comments: partial completion

INV4/pallet-inv4/Cargo.toml, INV4/pallet-inv4/src/ipl.rs, INV4/pallet-inv4/src/ips.rs, INV4/pallet-inv4/src/ipt.rs, INV4/pallet-inv4/src/lib.rs, INV4/pallet-inv4/src/util.rs, INV4/pallet-ipf/Cargo.toml, INV4/pallet-ipf/src/lib.rs, primitives/Cargo.toml, primitives/src/lib.rs
Closes #175 and solves some other issues found on the way. Also upgrades RMRK pallets to the latest version available and removes WASM permissions from IPL.
=> Pre-launch fixes and upgrades

INV4/pallet-inv4/src/account_derivation.rs, INV4/pallet-inv4/src/dispatch.rs, INV4/pallet-inv4/src/fee_handling.rs, INV4/pallet-inv4/src/inv4_core.rs, INV4/pallet-inv4/src/lib.rs, INV4/pallet-inv4/src/lookup.rs, INV4/pallet-inv4/src/multisig.rs, INV4/pallet-inv4/src/origin.rs, INV4/pallet-inv4/src/voting.rs
Every helper module got it's own documentation.
eg pallet_inv4::fee_handling
=> Reworked INV4 documentation

Cargo.toml, INV4/pallet-inv4/Cargo.toml, INV4/pallet-inv4/src/account_derivation.rs, INV4/pallet-inv4/src/dispatch.rs, INV4/pallet-inv4/src/lib.rs, INV4/pallet-inv4/src/origin.rs, INV4/pallet-inv4/src/tests/mock.rs, INV4/pallet-inv4/src/tests/mod.rs, INV4/pallet-inv4/src/voting.rs, OCIF/staking/Cargo.toml, OCIF/staking/src/lib.rs, OCIF/staking/src/testing/mock.rs, README.md, pallet-checked-inflation/Cargo.toml, pallet-checked-inflation/src/lib.rs, pallet-checked-inflation/src/mock.rs, pallet-rings/Cargo.toml, pallet-rings/src/lib.rs, pallet-rings/src/tests/mock.rs, pallet-rings/src/traits.rs, primitives/Cargo.toml, rust-toolchain.toml
=> Upgrade Polkadot SDK version to v1.6.0
